services:
  users_service:
    container_name: users
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: User
    ports:
      - '5450:5432'
    volumes:
      - UserData:/var/lib/postgresql/data
  content_service:
    container_name: content
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Content
    ports:
      - '5451:5432'
    volumes:
      - ContentData:/var/lib/postgresql/data
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=redispass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6380:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  UserData: {}
  ContentData: {}
  redis_data: {}