spring:
  application:
    name: backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
   redis:
    host: localhost
    port: 6380  # Redis'in dış portu
    password: redispass  # Redis için belirlenen şifre
    timeout: 2000
    database: 0

  datasource:
    first:
      url: jdbc:postgresql://localhost:5450/User
      username: root
      password: root
    second:
      url: jdbc:postgresql://localhost:5451/Content
      username: root
      password: root


